[workspace]
resolver = "2"
members = [
    "rscx",
    "rscx-macros",
    "benches",
]

[workspace.package]
version = "0.1.3"

[workspace.dependencies]
rscx = { path = "./rscx", version = "0.1.3" }
rscx-macros = { path = "./rscx-macros", version = "0.1.3" }
